

###
POST http://localhost:3000/api/seca/users
Content-Type: application/json

{
  "username": "test",
  "password": "test"
}


###
GET http://localhost:3000/api/seca/groups
Authorization: Bearer {{Token}}



###
POST http://localhost:3000/api/seca/groups
Content-Type: application/json
Authorization: Bearer {{Token}}

{
  "description": "desc",
  "name": "name"
}


###
GET http://localhost:3000/api/seca/groups/1
Authorization: Bearer {{Token}}


###
POST http://localhost:3000/api/seca/groups/1
Content-Type: application/json
Authorization: Bearer {{Token}}

{
  "id": ""
}


###
PUT http://localhost:3000/api/seca/groups/1
Content-Type: application/json
Authorization: Bearer {{Token}}

{}


###
DELETE http://localhost:3000/api/seca/groups/1
Authorization: Bearer {{Token}}


###
DELETE http://localhost:3000/api/seca/1/G5v0Z9Yc3YZz9
Authorization: Bearer {{Token}}


###
GET http://localhost:3000/api/seca/events


###
GET http://localhost:3000/api/seca/events/Chicago
